language: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
before_deploy:
- zip -r martholidayalarm *
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: martholidayalarm-deploy
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
    repo: hongsii/mart-holiday-alarm
    branch: master
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: martholidayalarm-deploy
  key: martholidayalarm.zip
  bundle_type: zip
  application: martholidayalarm
  deployment_group: martholidayalarm-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    repo: hongsii/mart-holiday-alarm
    branch: master
notifications:
  email:
    recipients:
    - pozt1234@gmail.com
  slack:
    rooms:
    - secure: oO7TASDUCg6LhKTrkJZc/J5mzpCQqvEfbRpcSfIdub3/dhtjCSALPBuzeh36I/DQhidcIUeUi2l1v6A411tPFAoUT0P2G5CxYRwh70Uv431cdHGu4VYTZfMma9J8Tr9LzMY5XSGlfQIshg97SBgr+hMUu+NJWHbg8PoQmerw6dJRLHTbWKvZDrKeZ8DDDiY25avaKeKLgUVxt7dctv9AZnlKRgcNBS0uRXZtYloDJrs8NDZuo1mbxvjePjf5gt0+gfxWrYtG/AhLwibRo+JU7Okb5va/Ury02UXPmmZFD8BAFrTtz2+B5R2S5WVW++y5Bsc9jEO51BYl+/0VFeCTxbKKf2sA6WqLkNLLq0LSDdIswNHx4BrEIExhvdxDYp5VMvGs2XQ8Zx3Ve4vzqBQ29aFyN027HLk/QG7DWAtElHsQUj1oYeY4ji2XRT+4BulOMPpolrXTGzXrwps/5sWvLzrKHs9n/eRANCrGzmIYptzmhAqWVU1cFjoyAWNOfxH3HvBK0k8YcUmcjmr1iEjXCUCzb0j+CVEZiWwkTXo2K9gGEqByojtiynVQ2cTWKFSn78HPWGDLMtgyxQM6vh5l5k6+cUs/2IPzXT56Tcx17OkstHhvjmgfVivR5/xQ2qemzoUc0EJw8TVQ/YvkLkA8S2xDjDI9T8qiAqu+LVDnVoA=
