server:
  port: 8080

spring:
  http:
    encoding:
      force: true
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  profiles: dev
  output:
    ansi.enabled: always
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: false
  datasource:
    hikari:
      connection-timeout: 10000
      max-lifetime: 10000

---

spring:
  profiles: prod1

server:
  port: 8081

---

spring:
  profiles: prod2

server:
  port: 8082
