spring:
  profiles:
    active: dev

server:
  port: 8080

management.endpoints.web.base-path: /

---

spring:
  profiles: dev
  output:
    ansi.enabled: always
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

---

spring:
  profiles: prod1

server:
  port: 8081

---

spring:
  profiles: prod2

server:
  port: 8082
