server:
  port: 8080

spring:
  http:
    encoding:
      force: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

---

spring:
  profiles: local
  output:
    ansi.enabled: always
  datasource:
    url: jdbc:mariadb://localhost:3306/martholidayalarm
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

---

spring:
  profiles: dev
  output:
    ansi.enabled: always
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

---

spring:
  profiles: prod1,dev1

server:
  port: 8081

---

spring:
  profiles: prod2,dev2

server:
  port: 8082
