name: build

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**.md'
  deployment:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPLOAD_DIR: deploy
      APP_NAME: mart-holiday-alarm

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Zip build files
      run: |
        sudo apt-get update
        sudo apt-get install zip unzip -qy
        zip -r $APP_NAME *
        ls
    - name: Upload build file to s3
      run: aws s3 cp "$APP_NAME.zip" s3://${{ secrets.PROD_AWS_BUCKET }}${UPLOAD_DIR:+/$UPLOAD_DIR/}
    - name: Deploy
      run: aws deploy create-deployment --application-name $APP_NAME --deployment-group-name "$APP_NAME-group" --s3-location bucket=${{ secrets.PROD_AWS_BUCKET }},bundleType=zip,key="${UPLOAD_DIR:+$UPLOAD_DIR/}${APP_NAME}.zip"

    - uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        author_name: '배포 결과'
        fields: repo,commit,message,action,ref,job,took
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
